### ISSUE TITLE
tapper.py SyntaxError: invalid syntax. Perhaps you forgot a comma?

### ISSUE THREAD

**Issue by tnttol** [YarmolenkoD/coub#8]
Traceback (most recent call last):
  File "/home/name/bots/coub/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/home/name/bots/coub/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/home/name/bots/coub/bot/utils/launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "/home/name/bots/coub/bot/core/tapper.py", line 225
    json=json_data

SyntaxError: invalid syntax. Perhaps you forgot a comma?

**Comment by Teddy-ke** [comment]
same problem
