### ISSUE TITLE
SyntaxError: invalid syntax. Perhaps you forgot a comma?

### ISSUE THREAD

**Issue by SeaXen** [YarmolenkoD/coub#9]
Traceback (most recent call last):
  File "D:\TG\BOT\coub\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "D:\TG\BOT\coub\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "D:\TG\BOT\coub\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "D:\TG\BOT\coub\bot\core\tapper.py", line 225
    json=json_data
         ^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

**Comment by Teddy-ke** [comment]
same problem
